## Predict the Value of MPG for given displacement and #Cylinders
## Using Neural Networks With Numpy

## Neural Network Architecture


**Number of Neurons:** 4

   Input layer-2

   Hidden layer-3

   Output layer-1
 

**Activation function:**  tanh (Input and Hidden)

**Weight initialization type** - Random init

**Bias:**  No bias taken as there is only one hidden layer and number of inputs are less.

**Back propogation:** Gradient descent.

**Epochs:** 1000

In [53]:
import numpy as np
import random

### Data Generation and Normalization

In [103]:
# X = (cylinders, displacement), y = score on test
cars_x = np.array(([6,160.0], [4,108.0], [3,168.0],[8,318],[8,304]), dtype=float) # input data as float for calculations
y = np.array(([21.0], [22.8], [21.4],[15.5],[15.2]), dtype=float) # output data as float for calcualtions

# Normalization
cars_x = cars_x/np.amax(cars_x, axis=0) # scaling input data
y = y/np.max(y) # scaling output data

# split data
X = np.split(cars_x, [5])[0] # training data
xPredicted = np.split(cars_x, [5])[1] # testing data

## Neural Network Class

In [104]:

class Neural_Network():

#function for forwrd pass and backward pass
  def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

    
  def __init__(self):
#number of neurons in each layer
    self.inputSize = 2
    self.outputSize = 1
    self.hiddenSize = 3

#weights attached between layers

# (3x2) weight matrix from input to hidden layer
    self.W1 = np.random.randn(self.inputSize, self.hiddenSize)
# (3x1) weight matrix from hidden to output layer    
    self.W2 = np.random.randn(self.hiddenSize, self.outputSize) 

#forward propagation through our network   

#Matrix multiplications using dot product function

  def forward(self, X):
    
    self.z = np.dot(X, self.W1) 
    self.z2 = self.tanh(self.z) # activation function for neurons to fire output to hidden layer
    self.z3 = np.dot(self.z2, self.W2) 
    o = self.tanh(self.z3) # final activation function for neurons to fire output to output layer
    return o #output

# activation function for neuron firing
  def tanh(self,s):
    return np.tanh(s)

#tanh_backward is function to find derivative, which helps in building GD algorithm in the end for back propagation
  def tanh_backward(self, s): 
    return (1-np.square(s))

# Backward propagation through the network to correct the weights
  def backward(self, X, y, o):
    
    self.o_error = y - o # error in output, differene in actual and predicted
    self.o_delta = self.o_error*self.tanh_backward(o) # applying derivative of sigmoid to error

    self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
    self.z2_delta = self.z2_error*self.tanh_backward(self.z2) # applying derivative of sigmoid to z2 error

#adjusting weights
    self.W1 += X.T.dot(self.z2_delta) 
    self.W2 += self.z2.T.dot(self.o_delta)
    

## Calculate the Results 

In [106]:
NN = Neural_Network()

for i in range(1001): #1000 epochs
  
  NN.train(X, y)

#After 1000 epochs, loss and outputs     
print("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) # mean sum squared loss    
print("# " + str(i) + "\n")
print("Input (scaled): \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" + str(NN.forward(X)))

Loss: 
0.04471871577980875
# 1000

Input (scaled): 
[[0.75       0.50314465]
 [0.5        0.33962264]
 [0.375      0.52830189]
 [1.         1.        ]
 [1.         0.95597484]]
Actual Output: 
[[0.92105263]
 [1.        ]
 [0.93859649]
 [0.67982456]
 [0.66666667]]
Predicted Output: 
[[0.99990974]
 [0.99945798]
 [0.9998933 ]
 [0.99999621]
 [0.99999483]]
